-- XRKR80HD Studio - Current Supabase Schema Patch
-- Run this in Supabase SQL Editor (safe to re-run).
-- This patch creates/fixes all tables currently used by the app, including:
-- tracks (XRKR Hub), bands + band_tracks, podcasts + episodes, local_businesses, blog_posts, projects, media_items, site_profiles.
-- It also ensures the "uploads" storage bucket supports audio/image uploads.

begin;

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- site_profiles
create table if not exists public.site_profiles (
  id bigint generated by default as identity primary key,
  headline varchar(255),
  welcome_message varchar(220),
  blog_notice_message varchar(180),
  short_bio varchar(300),
  full_bio text,
  avatar_url text,
  home_hub_card_image_url text,
  home_legends_card_image_url text,
  home_scene_card_image_url text,
  home_podcast_card_image_url text,
  home_business_card_image_url text,
  home_contact_card_image_url text,
  home_new_tracks_alert_enabled boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.site_profiles add column if not exists headline varchar(255);
alter table public.site_profiles add column if not exists welcome_message varchar(220);
alter table public.site_profiles add column if not exists blog_notice_message varchar(180);
alter table public.site_profiles add column if not exists short_bio varchar(300);
alter table public.site_profiles add column if not exists full_bio text;
alter table public.site_profiles add column if not exists avatar_url text;
alter table public.site_profiles add column if not exists home_hub_card_image_url text;
alter table public.site_profiles add column if not exists home_legends_card_image_url text;
alter table public.site_profiles add column if not exists home_scene_card_image_url text;
alter table public.site_profiles add column if not exists home_podcast_card_image_url text;
alter table public.site_profiles add column if not exists home_business_card_image_url text;
alter table public.site_profiles add column if not exists home_contact_card_image_url text;
alter table public.site_profiles add column if not exists home_new_tracks_alert_enabled boolean not null default false;
alter table public.site_profiles add column if not exists created_at timestamptz not null default now();
alter table public.site_profiles add column if not exists updated_at timestamptz not null default now();

drop trigger if exists trg_site_profiles_updated_at on public.site_profiles;
create trigger trg_site_profiles_updated_at
before update on public.site_profiles
for each row execute function public.set_updated_at();

-- tracks (owner XRKR Hub player)
create table if not exists public.tracks (
  id bigint generated by default as identity primary key,
  title varchar(255) not null,
  artist_name varchar(255) not null default 'xrkr80hd',
  genre varchar(80),
  description text,
  audio_url text not null,
  cover_image_url text,
  external_url text,
  release_date date,
  sort_order integer not null default 0,
  is_featured boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.tracks add column if not exists title varchar(255);
alter table public.tracks add column if not exists artist_name varchar(255) not null default 'xrkr80hd';
alter table public.tracks add column if not exists genre varchar(80);
alter table public.tracks add column if not exists description text;
alter table public.tracks add column if not exists audio_url text;
alter table public.tracks add column if not exists cover_image_url text;
alter table public.tracks add column if not exists external_url text;
alter table public.tracks add column if not exists release_date date;
alter table public.tracks add column if not exists sort_order integer not null default 0;
alter table public.tracks add column if not exists is_featured boolean not null default true;
alter table public.tracks add column if not exists created_at timestamptz not null default now();
alter table public.tracks add column if not exists updated_at timestamptz not null default now();

create index if not exists idx_tracks_sort_order on public.tracks(sort_order asc, release_date desc);
create index if not exists idx_tracks_featured on public.tracks(is_featured);

drop trigger if exists trg_tracks_updated_at on public.tracks;
create trigger trg_tracks_updated_at
before update on public.tracks
for each row execute function public.set_updated_at();

-- bands
create table if not exists public.bands (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  slug varchar(255) not null unique,
  era text not null default 'archive' check (era in ('archive', 'scene')),
  years_active varchar(60),
  genre varchar(80),
  genres_json jsonb not null default '[]'::jsonb,
  tagline varchar(180),
  summary varchar(320) not null,
  story text,
  image_url text,
  banner_image_url text,
  band_photo_url text,
  is_solo_artist boolean not null default false,
  is_published boolean not null default true,
  sort_order integer not null default 0,
  members_json jsonb not null default '{"members":[],"social_links":{}}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.bands add column if not exists name varchar(255);
alter table public.bands add column if not exists slug varchar(255);
alter table public.bands add column if not exists era text not null default 'archive';
alter table public.bands add column if not exists years_active varchar(60);
alter table public.bands add column if not exists genre varchar(80);
alter table public.bands add column if not exists genres_json jsonb not null default '[]'::jsonb;
alter table public.bands add column if not exists tagline varchar(180);
alter table public.bands add column if not exists summary varchar(320);
alter table public.bands add column if not exists story text;
alter table public.bands add column if not exists image_url text;
alter table public.bands add column if not exists banner_image_url text;
alter table public.bands add column if not exists band_photo_url text;
alter table public.bands add column if not exists is_solo_artist boolean not null default false;
alter table public.bands add column if not exists is_published boolean not null default true;
alter table public.bands add column if not exists sort_order integer not null default 0;
alter table public.bands add column if not exists members_json jsonb not null default '{"members":[],"social_links":{}}'::jsonb;
alter table public.bands add column if not exists created_at timestamptz not null default now();
alter table public.bands add column if not exists updated_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'bands_era_check'
      and conrelid = 'public.bands'::regclass
  ) then
    alter table public.bands
      add constraint bands_era_check check (era in ('archive', 'scene'));
  end if;
exception
  when others then
    null;
end $$;

create unique index if not exists idx_bands_slug on public.bands(slug);
create index if not exists idx_bands_era_sort on public.bands(era, sort_order asc, name asc);
create index if not exists idx_bands_published on public.bands(is_published);

drop trigger if exists trg_bands_updated_at on public.bands;
create trigger trg_bands_updated_at
before update on public.bands
for each row execute function public.set_updated_at();

-- band_tracks (tracks owned by each band)
create table if not exists public.band_tracks (
  id bigint generated by default as identity primary key,
  band_id bigint not null references public.bands(id) on delete cascade,
  title varchar(255) not null,
  description text,
  audio_url text not null,
  cover_image_url text,
  sort_order integer not null default 0,
  is_published boolean not null default true,
  include_in_radio boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.band_tracks add column if not exists band_id bigint;
alter table public.band_tracks add column if not exists title varchar(255);
alter table public.band_tracks add column if not exists description text;
alter table public.band_tracks add column if not exists audio_url text;
alter table public.band_tracks add column if not exists cover_image_url text;
alter table public.band_tracks add column if not exists sort_order integer not null default 0;
alter table public.band_tracks add column if not exists is_published boolean not null default true;
alter table public.band_tracks add column if not exists include_in_radio boolean not null default true;
alter table public.band_tracks add column if not exists created_at timestamptz not null default now();
alter table public.band_tracks add column if not exists updated_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'band_tracks_band_id_fkey'
      and conrelid = 'public.band_tracks'::regclass
  ) then
    alter table public.band_tracks
      add constraint band_tracks_band_id_fkey
      foreign key (band_id) references public.bands(id) on delete cascade;
  end if;
exception
  when others then
    null;
end $$;

create index if not exists idx_band_tracks_band_id on public.band_tracks(band_id);
create index if not exists idx_band_tracks_radio on public.band_tracks(is_published, include_in_radio, sort_order asc);

drop trigger if exists trg_band_tracks_updated_at on public.band_tracks;
create trigger trg_band_tracks_updated_at
before update on public.band_tracks
for each row execute function public.set_updated_at();

-- podcasts
create table if not exists public.podcasts (
  id bigint generated by default as identity primary key,
  title varchar(255) not null,
  slug varchar(255) not null unique,
  hosts varchar(255),
  topic varchar(120),
  summary varchar(320),
  description text,
  cover_image_url text,
  is_published boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.podcasts add column if not exists title varchar(255);
alter table public.podcasts add column if not exists slug varchar(255);
alter table public.podcasts add column if not exists hosts varchar(255);
alter table public.podcasts add column if not exists topic varchar(120);
alter table public.podcasts add column if not exists summary varchar(320);
alter table public.podcasts add column if not exists description text;
alter table public.podcasts add column if not exists cover_image_url text;
alter table public.podcasts add column if not exists is_published boolean not null default true;
alter table public.podcasts add column if not exists sort_order integer not null default 0;
alter table public.podcasts add column if not exists created_at timestamptz not null default now();
alter table public.podcasts add column if not exists updated_at timestamptz not null default now();

create unique index if not exists idx_podcasts_slug on public.podcasts(slug);
create index if not exists idx_podcasts_sort on public.podcasts(topic asc, sort_order asc, title asc);

drop trigger if exists trg_podcasts_updated_at on public.podcasts;
create trigger trg_podcasts_updated_at
before update on public.podcasts
for each row execute function public.set_updated_at();

-- podcast_episodes (episodes owned by each podcast)
create table if not exists public.podcast_episodes (
  id bigint generated by default as identity primary key,
  podcast_id bigint not null references public.podcasts(id) on delete cascade,
  slug varchar(255) not null unique,
  title varchar(255) not null,
  guest_names varchar(255),
  episode_number integer,
  summary varchar(320),
  description text,
  show_notes text,
  audio_url text not null,
  cover_image_url text,
  published_at timestamptz,
  sort_order integer not null default 0,
  is_explicit boolean not null default false,
  is_published boolean not null default true,
  include_in_radio boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.podcast_episodes add column if not exists podcast_id bigint;
alter table public.podcast_episodes add column if not exists slug varchar(255);
alter table public.podcast_episodes add column if not exists title varchar(255);
alter table public.podcast_episodes add column if not exists guest_names varchar(255);
alter table public.podcast_episodes add column if not exists episode_number integer;
alter table public.podcast_episodes add column if not exists summary varchar(320);
alter table public.podcast_episodes add column if not exists description text;
alter table public.podcast_episodes add column if not exists show_notes text;
alter table public.podcast_episodes add column if not exists audio_url text;
alter table public.podcast_episodes add column if not exists cover_image_url text;
alter table public.podcast_episodes add column if not exists published_at timestamptz;
alter table public.podcast_episodes add column if not exists sort_order integer not null default 0;
alter table public.podcast_episodes add column if not exists is_explicit boolean not null default false;
alter table public.podcast_episodes add column if not exists is_published boolean not null default true;
alter table public.podcast_episodes add column if not exists include_in_radio boolean not null default true;
alter table public.podcast_episodes add column if not exists created_at timestamptz not null default now();
alter table public.podcast_episodes add column if not exists updated_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'podcast_episodes_podcast_id_fkey'
      and conrelid = 'public.podcast_episodes'::regclass
  ) then
    alter table public.podcast_episodes
      add constraint podcast_episodes_podcast_id_fkey
      foreign key (podcast_id) references public.podcasts(id) on delete cascade;
  end if;
exception
  when others then
    null;
end $$;

create unique index if not exists idx_podcast_episodes_slug on public.podcast_episodes(slug);
create index if not exists idx_podcast_episodes_podcast on public.podcast_episodes(podcast_id, sort_order asc, published_at desc);
create index if not exists idx_podcast_episodes_radio on public.podcast_episodes(is_published, include_in_radio, sort_order asc);

drop trigger if exists trg_podcast_episodes_updated_at on public.podcast_episodes;
create trigger trg_podcast_episodes_updated_at
before update on public.podcast_episodes
for each row execute function public.set_updated_at();

-- local_businesses
create table if not exists public.local_businesses (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  category varchar(120),
  summary varchar(320),
  description text,
  logo_url text,
  website_url text,
  is_published boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.local_businesses add column if not exists name varchar(255);
alter table public.local_businesses add column if not exists category varchar(120);
alter table public.local_businesses add column if not exists summary varchar(320);
alter table public.local_businesses add column if not exists description text;
alter table public.local_businesses add column if not exists logo_url text;
alter table public.local_businesses add column if not exists website_url text;
alter table public.local_businesses add column if not exists is_published boolean not null default true;
alter table public.local_businesses add column if not exists sort_order integer not null default 0;
alter table public.local_businesses add column if not exists created_at timestamptz not null default now();
alter table public.local_businesses add column if not exists updated_at timestamptz not null default now();

create index if not exists idx_local_businesses_sort on public.local_businesses(sort_order asc, name asc);
create index if not exists idx_local_businesses_published on public.local_businesses(is_published);

drop trigger if exists trg_local_businesses_updated_at on public.local_businesses;
create trigger trg_local_businesses_updated_at
before update on public.local_businesses
for each row execute function public.set_updated_at();

-- blog_posts
create table if not exists public.blog_posts (
  id bigint generated by default as identity primary key,
  title varchar(255) not null,
  slug varchar(255) not null unique,
  author_username text,
  excerpt varchar(300),
  content text not null,
  cover_image_url text,
  published_at timestamptz,
  is_published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.blog_posts add column if not exists title varchar(255);
alter table public.blog_posts add column if not exists slug varchar(255);
alter table public.blog_posts add column if not exists author_username text;
alter table public.blog_posts add column if not exists excerpt varchar(300);
alter table public.blog_posts add column if not exists content text;
alter table public.blog_posts add column if not exists cover_image_url text;
alter table public.blog_posts add column if not exists published_at timestamptz;
alter table public.blog_posts add column if not exists is_published boolean not null default false;
alter table public.blog_posts add column if not exists created_at timestamptz not null default now();
alter table public.blog_posts add column if not exists updated_at timestamptz not null default now();

create unique index if not exists idx_blog_posts_slug on public.blog_posts(slug);
create index if not exists idx_blog_posts_published on public.blog_posts(is_published, published_at desc);
create index if not exists idx_blog_posts_author on public.blog_posts(author_username, created_at desc);

drop trigger if exists trg_blog_posts_updated_at on public.blog_posts;
create trigger trg_blog_posts_updated_at
before update on public.blog_posts
for each row execute function public.set_updated_at();

-- blog_channels (per-admin blog channel settings)
create table if not exists public.blog_channels (
  id bigint generated by default as identity primary key,
  username text not null unique,
  channel_name varchar(120) not null,
  channel_slug varchar(140) not null unique,
  blogger_bio text,
  avatar_url text,
  card_image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.blog_channels add column if not exists username text;
alter table public.blog_channels add column if not exists channel_name varchar(120);
alter table public.blog_channels add column if not exists channel_slug varchar(140);
alter table public.blog_channels add column if not exists blogger_bio text;
alter table public.blog_channels add column if not exists avatar_url text;
alter table public.blog_channels add column if not exists card_image_url text;
alter table public.blog_channels add column if not exists created_at timestamptz not null default now();
alter table public.blog_channels add column if not exists updated_at timestamptz not null default now();

create unique index if not exists idx_blog_channels_username on public.blog_channels(username);
create unique index if not exists idx_blog_channels_slug on public.blog_channels(channel_slug);

drop trigger if exists trg_blog_channels_updated_at on public.blog_channels;
create trigger trg_blog_channels_updated_at
before update on public.blog_channels
for each row execute function public.set_updated_at();

-- projects (read on pages; legacy/admin support)
create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title varchar(255) not null,
  slug varchar(255) unique,
  summary text,
  body text,
  cover_image_url text,
  project_url text,
  repo_url text,
  is_featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.projects add column if not exists title varchar(255);
alter table public.projects add column if not exists slug varchar(255);
alter table public.projects add column if not exists summary text;
alter table public.projects add column if not exists body text;
alter table public.projects add column if not exists cover_image_url text;
alter table public.projects add column if not exists project_url text;
alter table public.projects add column if not exists repo_url text;
alter table public.projects add column if not exists is_featured boolean not null default false;
alter table public.projects add column if not exists created_at timestamptz not null default now();
alter table public.projects add column if not exists updated_at timestamptz not null default now();

create index if not exists idx_projects_created on public.projects(created_at desc);

drop trigger if exists trg_projects_updated_at on public.projects;
create trigger trg_projects_updated_at
before update on public.projects
for each row execute function public.set_updated_at();

-- media_items (photo/video/audio gallery)
create table if not exists public.media_items (
  id bigint generated by default as identity primary key,
  title varchar(255),
  type varchar(20) not null,
  thumbnail_url text,
  media_url text not null,
  caption text,
  is_featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.media_items add column if not exists title varchar(255);
alter table public.media_items add column if not exists type varchar(20);
alter table public.media_items add column if not exists thumbnail_url text;
alter table public.media_items add column if not exists media_url text;
alter table public.media_items add column if not exists caption text;
alter table public.media_items add column if not exists is_featured boolean not null default false;
alter table public.media_items add column if not exists created_at timestamptz not null default now();
alter table public.media_items add column if not exists updated_at timestamptz not null default now();

create index if not exists idx_media_items_type_created on public.media_items(type, created_at desc);

drop trigger if exists trg_media_items_updated_at on public.media_items;
create trigger trg_media_items_updated_at
before update on public.media_items
for each row execute function public.set_updated_at();

-- Ensure one profile row exists for homepage settings UI
insert into public.site_profiles (headline)
select 'XRKR80HD'
where not exists (select 1 from public.site_profiles);

-- Row Level Security (RLS) hardening
alter table public.site_profiles enable row level security;
alter table public.tracks enable row level security;
alter table public.bands enable row level security;
alter table public.band_tracks enable row level security;
alter table public.podcasts enable row level security;
alter table public.podcast_episodes enable row level security;
alter table public.local_businesses enable row level security;
alter table public.blog_posts enable row level security;
alter table public.projects enable row level security;
alter table public.media_items enable row level security;

do $$
declare
  tbl text;
  pol record;
  managed_tables text[] := array[
    'site_profiles',
    'tracks',
    'bands',
    'band_tracks',
    'podcasts',
    'podcast_episodes',
    'local_businesses',
    'blog_posts',
    'projects',
    'media_items'
  ];
begin
  foreach tbl in array managed_tables loop
    for pol in
      select policyname
      from pg_policies
      where schemaname = 'public'
        and tablename = tbl
    loop
      execute format('drop policy if exists %I on public.%I', pol.policyname, tbl);
    end loop;
  end loop;

  if to_regclass('public.admin_users') is not null then
    execute 'alter table public.admin_users enable row level security';

    for pol in
      select policyname
      from pg_policies
      where schemaname = 'public'
        and tablename = 'admin_users'
    loop
      execute format('drop policy if exists %I on public.admin_users', pol.policyname);
    end loop;
  end if;
end $$;

create policy "Public read site profile"
on public.site_profiles
for select
to anon, authenticated
using (true);

create policy "Public read featured tracks"
on public.tracks
for select
to anon, authenticated
using (is_featured = true);

create policy "Public read published bands"
on public.bands
for select
to anon, authenticated
using (is_published = true);

create policy "Public read published band tracks"
on public.band_tracks
for select
to anon, authenticated
using (
  is_published = true
  and exists (
    select 1
    from public.bands b
    where b.id = band_tracks.band_id
      and b.is_published = true
  )
);

create policy "Public read published podcasts"
on public.podcasts
for select
to anon, authenticated
using (is_published = true);

create policy "Public read published podcast episodes"
on public.podcast_episodes
for select
to anon, authenticated
using (
  is_published = true
  and exists (
    select 1
    from public.podcasts p
    where p.id = podcast_episodes.podcast_id
      and p.is_published = true
  )
);

create policy "Public read published businesses"
on public.local_businesses
for select
to anon, authenticated
using (is_published = true);

create policy "Public read published blog posts"
on public.blog_posts
for select
to anon, authenticated
using (is_published = true);

create policy "Public read projects"
on public.projects
for select
to anon, authenticated
using (true);

create policy "Public read media items"
on public.media_items
for select
to anon, authenticated
using (true);

-- Storage bucket and MIME support for uploads (images + audio)
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'uploads',
  'uploads',
  true,
  209715200,
  array[
    'image/jpeg',
    'image/png',
    'image/webp',
    'audio/mpeg',
    'audio/wav',
    'audio/ogg',
    'audio/mp4',
    'audio/flac'
  ]::text[]
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Public read access for uploaded files (site media/audio playback)
drop policy if exists "Public read uploads bucket" on storage.objects;
create policy "Public read uploads bucket"
on storage.objects
for select
to public
using (bucket_id = 'uploads');

commit;
