import {NextResponse} from 'next/server';
import {createHash} from 'node:crypto';
import {getAdminConfig,matchEnvAdminCredentials} from '../../../../lib/admin-auth';
import {verifyPassword} from '../../../../lib/password-hash';
import {GAME_COOKIE,signGameSession,gameCredentialVersion} from '../../../../lib/game-night-session.mjs';
import {gameDb,gameIdentity,isGameOwner,sameOrigin,smallJson,privateHeaders} from '../../../../lib/game-night-server';
export const runtime='nodejs';export const dynamic='force-dynamic';
export async function GET(request){const user=await gameIdentity(request);return NextResponse.json(user||{error:'Please log in'},{status:user?200:401,headers:privateHeaders});}
export async function POST(request){if(!sameOrigin(request))return NextResponse.json({error:'Invalid request origin'},{status:403});try{const db=gameDb();const ip=request.headers.get('x-forwarded-for')?.split(',')[0]?.trim()||'unknown';const key=createHash('sha256').update(ip).digest('hex');const rate=await db.rpc('game_night_login_attempt',{attempt_key:key});if(rate.error||!rate.data)return NextResponse.json({error:'Too many attempts. Try again in 15 minutes.'},{status:429});const body=await smallJson(request,4096);const username=String(body.username||'').trim().toLowerCase();const password=String(body.password||'');let valid=false,credentialVersion=null;const envUser=matchEnvAdminCredentials(username,password);if(envUser&&isGameOwner(envUser))valid=true;else{const {data}=await db.from('game_night_hosts').select('password_hash,is_enabled').eq('username',username).maybeSingle();valid=!!data?.is_enabled&&verifyPassword(password,data.password_hash);if(valid)credentialVersion=gameCredentialVersion(data.password_hash,getAdminConfig().sessionToken);}if(!valid)return NextResponse.json({error:'Invalid username or password'},{status:401});const response=NextResponse.json({ok:true},{headers:privateHeaders});response.cookies.set({name:GAME_COOKIE,value:signGameSession(username,getAdminConfig().sessionToken,Date.now(),credentialVersion),httpOnly:true,secure:true,sameSite:'strict',path:'/',maxAge:7*86400});return response;}catch{return NextResponse.json({error:'Login unavailable. Please try again.'},{status:503});}}
export async function DELETE(request){if(!sameOrigin(request))return NextResponse.json({error:'Invalid origin'},{status:403});const response=NextResponse.json({ok:true},{headers:privateHeaders});response.cookies.set({name:GAME_COOKIE,value:'',httpOnly:true,secure:true,sameSite:'strict',path:'/',maxAge:0});return response;}
